27815 make httprequest copyconstructible
Polymedia/QWebApp pull request #3
Opened 2020-03-05 11:43 UTC by AlexanderBurtasov

https://visiology.tpondemand.com/entity/27815-sdelat-httprequest-copy-constructible

2020-03-05 12:05 UTC, AlexNik requested changes

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httpconnectionhandler.cpp
> +#include "server/http/httperror.h"
давай не будем мешать стили

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httprequest.cpp
> +const QByteArray &HttpRequest::getMethod() const
давай не будем мешать стили
тут качок слева
и везде ниже тоже

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httprequest.h
> +    const QByteArray &getMethod() const;
давай не будем мешать стили

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httprequesthandler.h
> -    virtual ~HttpRequestHandler();
а что делать с деструктором?

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httprequest.h
> -    virtual ~HttpRequest();
куда деструктор?

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httpresponse.cpp
> +void HttpResponse::setHeader(const QByteArray &name, const QByteArray &value)
давай не будем мешать стили

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httpresponse.cpp
> +    int remaining = data.size();
у равенства нет пробелов вокруг
давай не будем мешать стили

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httpsession.cpp
> +    const QByteArray EMPTY_ARRAY{};
я где-то это уже видел)

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/httpsession.cpp
> +        qDebug("HttpSession: (operator=) session %s refCount=%i", dataPtr->id.constData(), dataPtr->refCount);
давай не будем мешать стили

2020-03-05 12:05 UTC, AlexNik commented on QtWebApp/httpserver/staticfilecontroller.cpp
> +    QByteArray path = request.getPath();
давай не будем мешать стили

2020-03-05 12:15 UTC, stmotw commented on QtWebApp/httpserver/httprequest.cpp
> +const QByteArray &HttpRequest::getMethod() const
Это ж студия автоформатирует

2020-03-05 12:41 UTC, AlexanderBurtasov commented on QtWebApp/httpserver/httprequest.h
> -    virtual ~HttpRequest();
Нет его больше: мы заменили указатели на владеющие ресурсом примитивы. Других виртуальных методов в классе нет. Ну и зачем он нам?

2020-03-05 14:51 UTC, AlexanderBurtasov commented on QtWebApp/httpserver/httprequesthandler.h
> -    virtual ~HttpRequestHandler();
Он был пустой. Т.к. HttpRequestHandler - потомок QObject - у него виртуальный деструктор от рождения. Зачем нам лишний код?

2020-03-05 15:01 UTC, AlexanderBurtasov commented on QtWebApp/httpserver/httpconnectionhandler.cpp
> +#include "server/http/httperror.h"
Не будем!

2020-03-06 11:46 UTC, AlexanderBurtasov commented on QtWebApp/httpserver/staticfilecontroller.cpp
> +    QByteArray path = request.getPath();
не будем!

2020-03-11 08:50 UTC, closed without merging