Add headers handler logic.
Polymedia/QWebApp pull request #7
Opened 2021-02-26 12:00 UTC by AlexNik

2021-03-10 14:14 UTC, AlexanderBurtasov requested changes

2021-03-10 14:14 UTC, AlexanderBurtasov commented on QtWebApp/httpserver/httpconnectionhandler.cpp
> +          while (socket->bytesToWrite()) socket->waitForBytesWritten();
Давай со след строки?

2021-03-10 14:14 UTC, AlexanderBurtasov commented on QtWebApp/httpserver/httpheadershandler.cpp
> +		return EMPTY_VALUE;
shift left

2021-03-10 15:08 UTC, AlexNik commented on QtWebApp/httpserver/httpconnectionhandler.cpp
> +          while (socket->bytesToWrite()) socket->waitForBytesWritten();
я старался придерживаться стиля стефанфрингса ,но он завернул мои ПР (((

2021-03-12 11:56 UTC, alex3fx commented on QtWebApp/httpserver/httprequest.cpp
> +}
Конструктор копирования разве автоматически не получится?

2021-03-12 11:57 UTC, alex3fx approved these changes

2021-03-12 13:57 UTC, AlexanderBurtasov approved these changes

2021-03-12 14:02 UTC, merged