HttpResponse write rapidjson
Polymedia/QWebApp pull request #8
Opened 2021-07-13 14:42 UTC by PoolBall

2021-07-13 14:59 UTC, alex3fx requested changes
minor fixes

2021-07-13 14:59 UTC, alex3fx commented on QtWebApp/httpserver/httpresponse.cpp
> +        void Flush() {
методы с маленькой буквы и public и private, так привычнее

2021-07-13 14:59 UTC, alex3fx commented on QtWebApp/httpserver/httpresponse.cpp
> +        char m_buffer[16384];
почему 16384?

2021-07-13 15:19 UTC, PoolBall commented on QtWebApp/httpserver/httpresponse.cpp
> +        void Flush() {
Put и Flush - это контракт с rapidjson::Writer

2021-07-13 15:20 UTC, PoolBall commented on QtWebApp/httpserver/httpresponse.cpp
> +        char m_buffer[16384];
А хз. Портировал код из HttpResponse::writeToSocket

2021-07-13 18:47 UTC, AlexNik requested changes

2021-07-13 18:47 UTC, AlexNik commented on QtWebApp/httpserver/httpresponse.h
> +#include <rapidjson/document.h>
так нельзя...
`QtWebApp` это отдельный проект, поэтому тебе надо добавить либу `rapidjson` в зависимости

2021-07-13 18:47 UTC, AlexNik commented on QtWebApp/httpserver/httpresponse.cpp
> +        size_t m_idxBuffer = 0;
`m_indexBuffer`

2021-07-13 18:47 UTC, AlexNik commented on QtWebApp/httpserver/httpresponse.cpp
> +            qint64 bytesToSend = m_idxBuffer;
size_t?

2021-07-16 10:06 UTC, alex3fx approved these changes

2021-07-16 10:12 UTC, AlexNik approved these changes

2021-07-16 10:34 UTC, merged